#!/usr/bin/env python3
"""Generate src/so101.cho, the SO-101's kinematic chain, from the URDF.

The numbers come from the file, not from a person: every joint on the path from `base_link` to
`gripper_frame_link`, its origin (`xyz`, `rpy`) and its axis, written as the URDF writes them. The URDF's angles are
truncated (`3.14159`, `1.5708`), and they are kept truncated: the point is to compute what LeRobot's placo computes
from the same file, not an idealised arm.

    python3 scripts/gen_chain.py tests/fixtures/urdf/so101_new_calib.urdf > src/so101.cho
    python3 scripts/gen_chain.py tests/fixtures/urdf/so101_new_calib.urdf --check src/so101.cho   # CI
"""
import hashlib
import sys
import xml.etree.ElementTree as ET

TIP = "gripper_frame_link"
MOVING = ["shoulder_pan", "shoulder_lift", "elbow_flex", "wrist_flex", "wrist_roll"]


def chain(urdf):
    joints = {j.find("child").get("link"): j for j in ET.parse(urdf).getroot().findall("joint")}
    path, link = [], TIP
    while link in joints:
        j = joints[link]
        path.append(j)
        link = j.find("parent").get("link")
    if link != "base_link":
        raise SystemExit(f"the chain from {TIP} ends at {link}, not base_link")
    return list(reversed(path))


def literal(s):
    # A cancho float literal for the URDF's decimal text, unchanged except for a missing point or exponent form.
    f = float(s)
    text = repr(f)
    return text if ("." in text or "e" in text or "inf" in text or "nan" in text) else text + ".0"


def generate(urdf):
    digest = hashlib.sha256(open(urdf, "rb").read()).hexdigest()
    js = chain(urdf)
    names = [j.get("name") for j in js]
    moving = [j.get("name") for j in js if j.get("type") == "revolute"]
    if moving != MOVING:
        raise SystemExit(f"unexpected moving joints {moving}")
    for j in js:
        if j.get("type") == "revolute":
            ax = j.find("axis").get("xyz").split()
            if [float(v) for v in ax] != [0.0, 0.0, 1.0]:
                raise SystemExit(f"{j.get('name')}: axis {ax}, this generator only knows z")
    out = []
    out.append("edition 5;\n\nmodule so101;\n")
    out.append("// GENERATED by scripts/gen_chain.py from tests/fixtures/urdf/so101_new_calib.urdf "
               f"(sha256 {digest[:16]}...). Do not edit;\n// regenerate, and CI checks that it matches.\n//\n"
               f"// The chain from base_link to {TIP}: " + " -> ".join(names) + ".\n"
               "// Every moving joint turns about its own z axis (checked by the generator).\n")
    out.append("// How many transforms make the chain: one per joint, the last one fixed.\n"
               f"pub fn transforms() -> [] int {{\n    return {len(js)};\n}}\n")
    out.append(f"// How many of them move: the first {len(MOVING)}, in this order: {', '.join(MOVING)}.\n"
               f"pub fn moving() -> [] int {{\n    return {len(MOVING)};\n}}\n")
    for field, attr in (("xyz", "xyz"), ("rpy", "rpy")):
        out.append(f"// The origin {field} of transform `k`, component `c` (0, 1, 2), as the URDF writes it.\n"
                   f"pub fn {field}(k: int, c: int) -> [] float {{")
        for k, j in enumerate(js):
            vals = j.find("origin").get(attr).split()
            for c, v in enumerate(vals):
                out.append(f"    if k == {k} && c == {c} {{\n        return {literal(v)};\n    }}")
        out.append("    return 0.0;\n}\n")
    return "\n".join(out)


def main():
    urdf = sys.argv[1]
    text = generate(urdf)
    if len(sys.argv) > 3 and sys.argv[2] == "--check":
        have = open(sys.argv[3]).read()
        if have != text:
            print(f"{sys.argv[3]} does not match {urdf}: regenerate with scripts/gen_chain.py")
            return 1
        print(f"{sys.argv[3]} matches {urdf}")
        return 0
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
